loopsocial/firework-android-sdk-examples

feedResources/app/src/main/AndroidManifest.xml
feedResources/app/src/main/java/tv/fw/example/MainActivity.kt
feedResources/app/src/main/java/tv/fw/example/channel/ChannelActivity.kt
feedResources/app/src/main/res/layout/activity_channel.xml

**What**
Create Channel screen
**How**
Add Channel screen as a separate activity.
https://user-images.githubusercontent.com/101661405/212079383-63040e5b-c8bc-4cfd-8354-f04a619129c3.mp4

FeedResource[PART4] Create Channel screen

---

feedResources/app/build.gradle.kts
feedResources/app/src/main/AndroidManifest.xml
feedResources/app/src/main/java/tv/fw/example/MainActivity.kt
feedResources/app/src/main/java/tv/fw/example/discovery/DiscoveryActivity.kt
feedResources/app/src/main/java/tv/fw/example/dynamiccontent/DynamicContentActivity.kt
feedResources/app/src/main/java/tv/fw/example/playlist/PlaylistActivity.kt
feedResources/app/src/main/res/layout/activity_dynamic_content.xml
feedResources/app/src/main/res/layout/dynamic_content_details.xml
feedResources/app/src/main/res/values/strings.xml

**What**
1. Create dynamic content screen
2. Fix screen titles
3. Change Channel Id to one which supports the dynamic content
**Screenshots**
https://user-images.githubusercontent.com/101661405/212100613-0945aa1c-df0e-4e6e-be11-31f1dacc2a7e.mp4

Feed resource [PART5] create dynamic content screen

---

feed_resources/app/build.gradle.kts
feed_resources/app/src/main/AndroidManifest.xml
feed_resources/app/src/main/java/tv/fw/example/ExampleApplication.kt
feed_resources/app/src/main/java/tv/fw/example/MainActivity.kt
feed_resources/app/src/main/java/tv/fw/example/channel/ChannelActivity.kt
feed_resources/app/src/main/java/tv/fw/example/discovery/DiscoveryActivity.kt
feed_resources/app/src/main/java/tv/fw/example/playlist/PlaylistActivity.kt
feed_resources/app/src/main/res/layout/activity_channel.xml
feed_resources/app/src/main/res/layout/activity_main.xml

**What**
Added destruction of feed view in activities.

Destroy feed in resources app

---

feed_integration/app/build.gradle.kts
feed_integration/app/src/main/java/tv/fw/feedintegration/ExampleApplication.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedListAdapter.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedListFragment.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedViewItem.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/ListItem.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/RecyclerViewIntegrationActivity.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/TextItem.kt
feed_integration/app/src/main/res/layout/activity_fragment_integration.xml
feed_integration/app/src/main/res/layout/activity_recycler_view.xml
feed_integration/app/src/main/res/layout/feed_list_item.xml
feed_integration/app/src/main/res/layout/fragment_feed_list.xml
feed_integration/app/src/main/res/layout/text_list_item.xml

**What**
Create recycler view integration screen
**Why**
- ASDK-990
**How**
Copy existent code from the SDK V2
**Video**
https://user-images.githubusercontent.com/101661405/212875926-983d5ad5-db33-4b3e-894c-7352fd27678f.mp4

Feed integration [PART2] Create recycler view integration screen

---

feed_integration/app/src/main/java/tv/fw/feedintegration/activity/ActivityIntegrationActivity.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/fragment/FeedViewFragment.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/fragment/FragmentIntegrationActivity.kt
feed_integration/app/src/main/res/layout/fragment_feed_view.xml

**What**
Create fragment integration screen
**Why**
ASDK-990
**How**
Create separate activity and fragment which contains `FwVideoFeedView`.
**Video**
https://user-images.githubusercontent.com/101661405/212888024-e0d2b446-bfec-4341-8930-fa2d0574f8ed.mp4

FeedView [PART3] integration fragment

---

feed_integration/app/build.gradle.kts
feed_integration/app/src/main/AndroidManifest.xml
feed_integration/app/src/main/java/tv/fw/feedintegration/ExampleApplication.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/activity/ActivityIntegrationActivity.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/addremove/AddRemoveIntegrationActivity.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/fragment/FeedViewFragment.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedListAdapter.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedListFragment.kt
feed_integration/app/src/main/java/tv/fw/feedintegration/recyclerview/FeedViewItem.kt
feed_integration/app/src/main/res/layout/activity_activity_integration.xml
feed_integration/app/src/main/res/layout/feed_list_item.xml
feed_integration/app/src/main/res/layout/fragment_feed_view.xml
feed_integration/build.gradle.kts
feed_integration/gradle/wrapper/gradle-wrapper.properties

Feed integration:  `6.0.0-beta.2` Update

---

shopping/app/build.gradle.kts
shopping/app/src/main/AndroidManifest.xml
shopping/app/src/main/java/tv/fw/example/shopping/ExampleApplication.kt
shopping/app/src/main/java/tv/fw/example/shopping/MainActivity.kt
shopping/app/src/main/java/tv/fw/example/shopping/shoppingcart/ShoppingCartAdapter.kt
shopping/app/src/main/java/tv/fw/example/shopping/shoppingcart/ShoppingCartFragment.kt
shopping/app/src/main/java/tv/fw/example/shopping/shoppingcart/ShoppingCartRepository.kt
shopping/app/src/main/res/layout/activity_main.xml
shopping/build.gradle.kts
shopping/gradle/wrapper/gradle-wrapper.properties
shopping/settings.gradle.kts

Updated demo app to use ` 6.0.0-beta.2` sdk version

Shopping:  `6.0.0-beta.2` Update

---

share_link/app/build.gradle.kts
share_link/app/src/main/AndroidManifest.xml
share_link/app/src/main/java/tv/fw/sharelink/ExampleApp.kt
share_link/app/src/main/java/tv/fw/sharelink/MainActivity.kt
share_link/app/src/main/java/tv/fw/sharelink/ShareLinkActivity.kt
share_link/app/src/main/res/layout/activity_main.xml
share_link/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
share_link/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
share_link/build.gradle.kts
share_link/gradle/wrapper/gradle-wrapper.properties
share_link/settings.gradle.kts

Sharelink:  `6.0.0-beta.2` Update

---

feed_resources/app/build.gradle.kts
feed_resources/app/src/main/AndroidManifest.xml
feed_resources/build.gradle.kts
feed_resources/gradle/wrapper/gradle-wrapper.properties

Feed resources:  `6.0.0-beta.2` Update

---

multi_host_livestream/app/build.gradle.kts
multi_host_livestream/app/src/main/AndroidManifest.xml
multi_host_livestream/app/src/main/java/tv/fw/example/multihostlivestream/ExampleApplication.kt
multi_host_livestream/app/src/main/java/tv/fw/example/multihostlivestream/MainActivity.kt
multi_host_livestream/app/src/main/res/layout/activity_main.xml
multi_host_livestream/build.gradle.kts
multi_host_livestream/gradle/wrapper/gradle-wrapper.properties
multi_host_livestream/settings.gradle.kts

Multi Host Livestream:  `6.0.0-beta.2` Update

---

compose/app/build.gradle.kts
compose/app/src/main/AndroidManifest.xml
compose/app/src/main/java/tv/fw/example/compose/ExampleApplication.kt
compose/app/src/main/java/tv/fw/example/compose/MainActivity.kt
compose/build.gradle.kts
compose/gradle/wrapper/gradle-wrapper.properties
compose/settings.gradle.kts

Compose:  `6.0.0-beta.2` Update

---

view_options/app/build.gradle.kts

https://github.com/loopsocial/firework_android_sdk_examples/actions/runs/4355853072/jobs/7613042519

Fix ViewOptions dependency version

---

compose/app/src/main/java/com/firework/example/compose/ui/theme/Theme.kt

https://github.com/loopsocial/firework_android_sdk_examples/actions/runs/4355853047/jobs/7613041911

Fix compose code format

---

compose/app/build.gradle.kts
feed_integration/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
share_link/app/src/main/java/com/firework/example/sharelink/Constants.kt
share_link/app/src/main/java/com/firework/example/sharelink/ExampleApp.kt
share_link/app/src/main/java/com/firework/example/sharelink/MainActivity.kt
share_link/app/src/main/java/com/firework/example/sharelink/ShareLinkActivity.kt
shopping/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
story_block/app/build.gradle.kts
story_block/app/src/main/res/layout/activity_main.xml
view_options/app/build.gradle.kts
view_options/app/src/main/java/com/firework/example/viewoptions/MainActivity.kt
view_options/app/src/main/res/layout/activity_main.xml

Updated example apps with `SDK v6.2.0`

Updated example apps with `SDK v6.2.0`

---

compose/app/build.gradle.kts
feed_integration/app/build.gradle.kts
feed_resources/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
shopping/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
story_block/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
Update example apps to the sdk version 6.2.1

Update example apps to the sdk version 6.2.1

---

story_block/app/build.gradle.kts
story_block/app/src/main/java/com/firework/example/storyblock/MainActivity.kt
story_block/app/src/main/res/layout/activity_main.xml

**What**
Update story block sample app to use 6.7.0
**Why**
- ASDK-1572
**How**
- Remove extra container from the layout. 
- Update init() function params

ASDK-1572: Update story block sample app to use 6.7.0

---

shopping/app/build.gradle.kts
shopping/app/src/main/java/com/firework/example/shopping/AddToCartModeActivity.kt
shopping/app/src/main/java/com/firework/example/shopping/ShopNowModeActivity.kt

**What**
Update shopping sample app to version 6.7.0
**Why**
ASDK-1572
**How**
- update shopping options params

ASDK-1572: Update shopping sample app to version 6.7.0

---

view_options/app/build.gradle.kts

**What**
- Update view options sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- Update view options sdk version to 6.7.0

ASDK-1572: Update view options sdk version to 6.7.0 part 8

---

single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Update singlehost sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- Update singlehost sdk version to 6.7.0

ASDK-1572: Update singlehost sdk version to 6.7.0 part 7

---

share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Update share link sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- Update share link sdk version to 6.7.0

ASDK-1572: Update share link sdk version to 6.7.0 part 6

---

compose/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Update picture in picture sdk version to 6.7.0 
**Why**
- ASDK-1572
**How**
- Update picture in picture sdk version to 6.7.0

ASDK-1572: Update picture in picture sdk version to 6.7.0 part 5

---

compose/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Update multihost sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- Update multihost sdk version to 6.7.0

ASDK-1572: Update multihost sdk version to 6.7.0 part 4

---

compose/app/build.gradle.kts
feed_resources/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- ASDK-1572: Update feed resource sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- ASDK-1572: Update feed resource sdk version to 6.7.0

ASDK-1572: Update feed resource sdk version to 6.7.0 part 3

---

compose/app/build.gradle.kts
feed_integration/app/build.gradle.kts
feed_resources/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- ASDK-1572: Update feed integration sdk version to 6.7.0
**Why**
- ASDK-1572
**How**
- ASDK-1572: Update feed integration sdk version to 6.7.0

ASDK-1572: Update feed integration sdk version to 6.7.0 part 2

---

compose/app/build.gradle.kts
compose/build.gradle.kts
compose/gradle/wrapper/gradle-wrapper.properties
feed_integration/app/build.gradle.kts
feed_resources/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- ASDK-1572: Update compose version to 6.7.0
**Why**
- ASDK-1572
**How**
- ASDK-1572: Update compose version to 6.7.0

ASDK-1572: Update compose version to 6.7.0 part 1

---

picture_in_picture/app/build.gradle.kts

**What**
- Fixing the write dex file crash
**Why**
- https://github.com/tiann/FreeReflection/issues/56
- https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading
**How**
- Downgrading the targetSdk to 33

Fix write dex file error

---

compose/app/build.gradle.kts
feed_integration/app/build.gradle.kts
feed_resources/app/build.gradle.kts
language/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
shopping/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
story_block/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Update to ASDK v6.14.2
**Why**
- ASDK-xxx or #xxx
**How**
-
**Screenshots**
|  Before   |   After   |
|-----------|-----------|
|   image   |   image   |

Update to ASDK v6.14.2

---

compose/app/build.gradle.kts
feed_integration/app/build.gradle.kts
feed_resources/app/build.gradle.kts
language/app/build.gradle.kts
multi_host_livestream/app/build.gradle.kts
picture_in_picture/app/build.gradle.kts
share_link/app/build.gradle.kts
shopping/app/build.gradle.kts
single_host_livestream/app/build.gradle.kts
story_block/app/build.gradle.kts
view_options/app/build.gradle.kts

**What**
- Upgrade native sdk version to 6.16.5
**Why**
- ASDK-xxx or #xxx
**How**
-
**Screenshots**
|  Before   |   After   |
|-----------|-----------|
|   image   |   image   |

Upgrade native sdk version to 6.16.5
